String html =
    "<html>\n"
    "\n"
    "<head>\n"
    "    <link rel=\"stylesheet\"\n"
    "href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/"
    "bootstrap.min.css\"\n"
    "integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/"
    "K68vbdEjh4u\" crossorigin=\"anonymous\">\n"
    "    <script>\n"
    "        function click_handler(b) {\n"
    "            btn = document.getElementById(b)\n"
    "            var x = new XMLHttpRequest()\n"
    "            switch (btn.value) {\n"
    "                case 'FORWARD':\n"
    "                    console.log(\"F\")\n"
    "                    x.open(\"GET\", \"/gpio/1\", true)\n"
    "                    break\n"
    "                case 'BACKWARD':\n"
    "                    console.log(\"B\")\n"
    "                    x.open(\"GET\", \"/gpio/2\", true)\n"
    "                    break\n"
    "                case 'LEFT':\n"
    "                    console.log(\"L\")\n"
    "                    x.open(\"GET\", \"/gpio/3\", true)\n"
    "                    break\n"
    "                case 'RIGHT':\n"
    "                    console.log(\"R\")\n"
    "                    x.open(\"GET\", \"/gpio/4\", true)\n"
    "                    break\n"
    "                case 'STOP':\n"
    "                    console.log(\"S\")\n"
    "                    x.open(\"GET\", \"/gpio/5\", true)\n"
    "                    break\n"
    "                default:\n"
    "                    console.log(\"ERR\")\n"
    "                    break\n"
    "            }\n"
    "\n"
    "            x.onload = function () {\n"
    "                alert(x.responseText)\n"
    "            }\n"
    "            x.send(null)\n"
    "        }\n"
    "    </script>\n"
    "    <style>\n"
    "        table {\n"
    "            text-align: center;\n"
    "            width: 100%;\n"
    "            border: 0px solid;\n"
    "        }\n"
    "\n"
    "        td {\n"
    "            text-align: center;\n"
    "            border: 0px solid;\n"
    "            padding: 10px;\n"
    "        }\n"
    "\n"
    "        input {\n"
    "            width: 100%;\n"
    "            height: 100px;\n"
    "            font-size: 3vw;\n"
    "        }\n"
    "    </style>\n"
    "</head>\n"
    "\n"
    "<body>\n"
    "    <table>\n"
    "        <tr>\n"
    "            <td></td>\n"
    "            <td><input class=\"btn btn-info\" type=\"button\" "
    "id=\"btn_fwd\" value=\"FORWARD\" onclick='click_handler(this.id)' "
    "/></td>\n"
    "            <td></td>\n"
    "        </tr>\n"
    "        <tr>\n"
    "            <td><input class=\"btn btn-info\" type=\"button\" "
    "id=\"btn_left\" value=\"LEFT\" onclick='click_handler(this.id)' /></td>\n"
    "            <td><input class=\"btn btn-danger\" type=\"button\" "
    "id=\"btn_stop\" value=\"STOP\" onclick='click_handler(this.id)' /></td>\n"
    "            <td><input class=\"btn btn-info\" type=\"button\" "
    "id=\"btn_right\" value=\"RIGHT\" onclick='click_handler(this.id)' "
    "/></td>\n"
    "        </tr>\n"
    "        <tr>\n"
    "            <td></td>\n"
    "            <td><input class=\"btn btn-info\" type=\"button\" "
    "id=\"btn_bwd\" value=\"BACKWARD\" onclick='click_handler(this.id)' "
    "/></td>\n"
    "            <td></td>\n"
    "        </tr>\n"
    "    </table>\n"
    "    <script "
    "src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/"
    "jquery.min.js\"></script>\n"
    "<script "
    "src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/"
    "bootstrap.min.js\"\n"
    "integrity=\"sha384-"
    "Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\"\n"
    "crossorigin=\"anonymous\"></script>\n"
    "</body>\n"
    "\n"
    "</html>\n"
    "";
